- main
vMimage: ubuntu-latest
Variables:
buildConfiguration: 'Release'
- script: dotnet build --configuration $(buildConfiguration)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
displayName: 'dotnet build $(buildConfiguration)' 

